# Generated by Django 5.0 on 2023-12-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsapp', '0003_rename_department_image_logo_logo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='model',
            field=models.TextField(unique=True),
        ),
    ]
